name: decoupled
recipe: drupal8
config:
  webroot: web
  php: 7.2
  via: nginx
  drush: path:/app/vendor/bin/drush
  database: mariadb:10.3
services:
  nodecompiler:
    type: node:8
tooling:
  npm: nodecompiler
  node: nodecompiler
